---
- name: 'Download Wordpress'
  get_url:
    url: https://br.wordpress.org/latest-pt_BR.tar.gz
    dest: '/tmp/wordpress.tar.gz'

- name: 'Descompactar'
  unarchive:
    remote_src: yes
    src: '/tmp/wordpress.tar.gz'
    dest: /var/www/
  become: yes

- name: 'Copia arquivos'
  copy:
    src: '{{ wp_instalation_dir }}/wp-config-sample.php'
    dest: '{{ wp_instalation_dir }}/wp-config.php'
    remote_src: yes
  become: yes

- name: 'Ajusta config-WP'
  replace:
    path: '{{ wp_instalation_dir }}/wp-config.php'
    regexp: '{{item.regex}}'
    replace: '{{item.value}}'
  with_items:
    - { regex: 'nome_do_banco_de_dados_aqui', value: '{{ wp_db_name }}' }
    - { regex: 'nome_de_usuario_aqui', value: '{{ wp_user_name }}' }
    - { regex: 'senha_aqui', value: '{{ wp_password }}' }
    - { regex: 'localhost', value: '{{ db_ip_machine }}' }
  become: yes

- name: 'Configura Apache para servir Wordpress'
  template:
    src: 'templates/000-default.conf'
    dest: '/etc/apache2/sites-available/000-default.conf'
  become: yes
  notify:
    - restart apache
