---
- name: 'Instala pacotes de dependencia do sistema operacional'
  apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
  become: yes
  loop:
    [
      'mysql-server',
      'mysql-client',
      'python-pymysql',
      'python3-dev',
      'libmysqlclient-dev',
    ]

- name: 'Instala pip3'
  apt:
    name: python3-pip
    state: present
    update_cache: yes
  become: yes

- name: 'Installing pip dependencies'
  pip:
    name: mysqlclient

# MySQL Configuration
- name: Set MySQL root password
  command: /usr/bin/mysql -e "alter user 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ db_root_password }}';"
  ignore_errors: yes
  become: yes

- name: 'Cria o banco do MySQL'
  mysql_db:
    name: '{{ wp_db_name }}'
    login_user: root
    login_password: root
    state: present

- name: 'Cria o usuário do MySQL'
  mysql_user:
    login_user: root
    login_password: root
    name: '{{ wp_user_name }}'
    password: '{{ wp_password }}'
    priv: '{{ wp_db_name }}.*:ALL'
    state: present
    host: '{{ item }}'
  loop: [
      '{{ wp_ip_machine }}', # wordpress machine
    ]

- name: 'Configura MySQL para aceitar conexões remotas'
  copy:
    src: 'files/mysqld.cnf'
    dest: '/etc/mysql/mysql.conf.d/mysqld.cnf'
  become: yes
  notify:
    - restart mysql
